const CategoriesActionTypes = {
  FETCH_DATA_START: 'FETCH_DTAT_START',
  FETCH_DATA_SUCCEESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const MealsActionTypes = {
  FETCH_DATA_START: 'FETCH_DTAT_START',
  FETCH_DATA_SUCCEESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

export { CategoriesActionTypes, MealsActionTypes };
